/**
 * install / uninstall command implementations.
 *
 * install writes ONLY under $HOME (per-user; no sudo, no cron, no launchd —
 * there is deliberately no privileged helper and no scheduler anywhere):
 *
 *   <base>/pipico/config.json      config skeleton (never overwritten)
 *   <base>/pipico/installed.json   the manifest of created resources
 *   <home>/.local/bin/pipico       the executable wrapper (never overwritten)
 *
 * where <base> is $XDG_CONFIG_HOME when set (it must resolve under $HOME or
 * install refuses), else $HOME/.config — the same base the config loader
 * uses. Existing files are never overwritten: they are kept untouched and
 * unlisted, so re-running is safe (idempotent) and uninstall never removes
 * anything pipico did not create. The manifest itself is written only when
 * absent. --dry-run prints the exact plan and writes nothing.
 *
 * install and uninstall never touch the Platform interface: they perform no
 * machine actions, only per-user file management.
 */
import { chmodSync, existsSync, mkdirSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Env } from './handlers/context.ts';
import type { CliIo } from './handlers/context.ts';
import { echoSafe } from './config.ts';
import { executablePath, bindingInstructions } from './bindings.ts';
import {
  hashContent,
  MANIFEST_FILENAME,
  manifestPathFor,
  serializeManifest,
  type ManifestResource,
} from './manifest.ts';

export type { Env };

export interface InstallRuntime {
  /** Absolute path of the bun binary the wrapper must exec. */
  bunPath: string;
  /** Absolute path of the cli.ts entry the wrapper must run. */
  cliPath: string;
}

/** The runtime the real CLI runs under (used unless a test injects one). */
export function defaultRuntime(): InstallRuntime {
  return { bunPath: process.execPath, cliPath: Bun.main };
}

export interface PlannedDir {
  kind: 'dir';
  path: string;
}

export interface PlannedFile {
  kind: 'file';
  path: string;
  content: string;
  mode: number;
  what: string;
}

export type PlannedResource = PlannedDir | PlannedFile;

/** The per-user wrapper: a tiny POSIX script running the pinned bun+cli. */
export function wrapperScript(runtime: InstallRuntime): string {
  return [
    '#!/usr/bin/env sh',
    '# pipico wrapper generated by "pipico install" (per-user; safe to delete).',
    '# It only ever execs the pinned bun and cli.ts recorded below, passing',
    '# arguments through verbatim. No shell evaluation of the arguments.',
    `exec ${shQuote(runtime.bunPath)} ${shQuote(runtime.cliPath)} "$@"`,
    '',
  ].join('\n');
}

/** Quote one path for the wrapper script (POSIX single-quote rule). */
export function shQuote(s: string): string {
  return `'${s.replaceAll("'", `'\\''`)}'`;
}

/** The config skeleton written when no config exists yet (a valid config). */
export function configSkeleton(home: string): string {
  const skeleton = {
    workspaces: {
      devops: {
        label: 'DevOps',
        app: 'com.apple.Terminal',
        paths: [join(home, 'work')],
        urls: [],
      },
    },
    attentionUrl: 'https://attention.example/today',
    incident: {
      notesRoot: join(home, 'incidents'),
      monitoringUrls: ['https://status.example/internal'],
    },
    study: { urls: ['https://course.example/lesson-1'] },
  };
  return `${JSON.stringify(skeleton, null, 2)}\n`;
}

/**
 * The config base directory: $XDG_CONFIG_HOME when set (must be absolute and
 * under $HOME), else $HOME/.config — the same base as the config loader.
 */
export function configBaseFor(env: Env): { ok: true; base: string } | { ok: false; error: string } {
  const home = env.HOME;
  if (home === undefined || home === '') {
    return { ok: false, error: 'HOME is not set; refusing to guess an install location' };
  }
  const homeNorm = home.replace(/\/+$/, '');
  if (homeNorm === '' || homeNorm === '/') {
    return { ok: false, error: 'HOME is empty or "/"; refusing to install' };
  }
  const xdg = env.XDG_CONFIG_HOME;
  if (xdg !== undefined && xdg !== '') {
    const base = xdg.replace(/\/+$/, '');
    if (!base.startsWith('/') || base === '/' || !base.startsWith(`${homeNorm}/`)) {
      return {
        ok: false,
        error: `XDG_CONFIG_HOME (${echoSafe(xdg)}) must be an absolute path under HOME: pipico writes only under $HOME`,
      };
    }
    return { ok: true, base };
  }
  return { ok: true, base: join(homeNorm, '.config') };
}

/** The ordered install plan: directories first (shallow), then files. */
export function planInstall(home: string, configBase: string, runtime: InstallRuntime): PlannedResource[] {
  const homeNorm = home.replace(/\/+$/, '');
  const dirs = [...new Set([configBase, join(configBase, 'pipico'), join(homeNorm, '.local'), join(homeNorm, '.local/bin')])]
    .sort((a, b) => a.split('/').length - b.split('/').length || a.localeCompare(b));
  return [
    ...dirs.map((path) => ({ kind: 'dir' as const, path })),
    {
      kind: 'file' as const,
      path: join(configBase, 'pipico/config.json'),
      content: configSkeleton(homeNorm),
      mode: 0o644,
      what: 'config skeleton',
    },
    {
      kind: 'file' as const,
      path: executablePath(homeNorm),
      content: wrapperScript(runtime),
      mode: 0o755,
      what: 'per-user wrapper',
    },
  ];
}

function describeEntry(r: PlannedResource): string {
  return r.kind === 'dir' ? `directory ${r.path}` : `file ${r.path} (${r.what})`;
}

export async function runInstallCommand(
  dryRun: boolean,
  env: Env,
  io: CliIo,
  runtime: InstallRuntime = defaultRuntime(),
): Promise<number> {
  const base = configBaseFor(env);
  if (!base.ok) {
    io.err(`error: install: ${base.error}`);
    return 1;
  }
  const home = env.HOME!.replace(/\/+$/, '');
  const manifestPath = manifestPathFor(base.base);

  io.out(dryRun ? 'install: dry run; nothing will be created (HOME unchanged)' : `install: writing only under ${home}`);
  const created: ManifestResource[] = [];

  for (const entry of planInstall(home, base.base, runtime)) {
    if (existsSync(entry.path)) {
      io.out(`install: exists, keeping it (never overwritten, not listed in the manifest): ${entry.path}`);
      continue;
    }
    if (dryRun) {
      io.out(`install: would create ${describeEntry(entry)}`);
      continue;
    }
    if (entry.kind === 'dir') {
      mkdirSync(entry.path); // parents are created earlier in the plan
      created.push({ path: entry.path, type: 'dir' });
    } else {
      writeFileSync(entry.path, entry.content, { flag: 'wx' });
      chmodSync(entry.path, entry.mode);
      created.push({ path: entry.path, type: 'file', sha256: hashContent(entry.content), mode: entry.mode.toString(8).padStart(4, '0') });
    }
    io.out(`install: created ${describeEntry(entry)}`);
  }

  if (existsSync(manifestPath)) {
    io.out(`install: manifest already exists, keeping it (never overwritten): ${manifestPath}`);
  } else if (dryRun) {
    io.out(`install: would create file ${manifestPath} (${MANIFEST_FILENAME}, listing the created resources)`);
  } else {
    writeFileSync(manifestPath, serializeManifest(created), { flag: 'wx' });
    io.out(`install: created file ${manifestPath} (${created.length} resources listed)`);
  }

  // Binding guidance, with the absolute path install creates — both in the
  // dry run and in the real run (VAL-HOST-034).
  for (const line of bindingInstructions(executablePath(home))) io.out(line);

  if (!dryRun) io.out(`install: done${created.length === 0 ? ' (already installed; nothing changed)' : ''}`);
  return 0;
}
